### ISSUE TITLE
Not responsive

### ISSUE THREAD

**Issue by rabia-aaziz** [sarariazahmedkhan/9-may-test#13]
please responsive karain

**Comment by sarariazahmedkhan** [comment]
#13wo woking me hai

**Comment by sarariazahmedkhan** [comment]
#13 solve

**Comment by rabia-aaziz** [comment]
issues aap ko close nahi karni
![not perfect](https://user-images.githubusercontent.com/39001798/58046468-3ae4da00-7afa-11e9-86ac-48fe82c769d4.PNG)
