### ISSUE TITLE
your work is not perfect

### ISSUE THREAD

**Issue by rabia-aaziz** [sarariazahmedkhan/9-may-test#7]
1) aapnay body pay background color apply nahi kiya.
2)icon size sahi nahi hai .
3)Nav bar k content or font family teek karain.
4)mobile screen pay nav bar pay hamburger ka icon aana chaiye.
5)img ki size teek  nahi hai or border b nahi di.
6)stars icons  perfect nahi hain.
7)hr ki tag ki jagha  border bottom use karain to behtar hai.
8)button b aapka sahi nahi hai.

**Comment by sarariazahmedkhan** [comment]
#7 ab sb solve hai ..plx re check karen
